export default `
// <!-- AUTOGENERATED CONTENT START --->
//
//  Available args: 
//  <!-- ARG DEFINITION --->
//  
//  == Storybook Args (not used by component) == 
//  story: string - This is what renders inside of the component. 
//
// <!-- AUTOGENERATED CONTENT END --->

export const userConfig =  {
  title: "Content/Component Name",
  component: 'component-name',
  argTypes: {
    // you can override argTypes here
    // statusType :{
    //   control: {
    //     type: 'select',
    //     options: ['nothing']
    //   },
    // }
  },
  args: {
 <!-- ARGS --->
    story: \`\`
  },
  parameters: {
    docs: {
      // figure out what the hell this thing does
      description: {
        component: \`,
      },
      source: {
        // This code sample will be used for every example unless overridden.
        code: \`
<component-name
<!-- ATTRIBUTES --->
>
<!-- SLOTS --->
</component-name>
        \`,
      },
    },
  },
};
`