// @ts-ignore - until I can figure out the args issue with new args, add a new arg to custom elements json and 
// run the update story command to test
// <!-- AUTOGENERATED CONTENT START --->
//
//  Available args: 
//  <!-- ARG DEFINITION --->
//  
//  == Storybook Args (not used by component) == 
//  story: string - This is what renders inside of the component. 
//
// <!-- AUTOGENERATED CONTENT END --->

export const userConfig =  {
  title: "Content/Test Component",
  component: 'test-component',
  argTypes: {
    // you can override argTypes here
    // statusType :{
    //   control: {
    //     type: 'select',
    //     options: ['nothing']
    //   },
    // }
  },
  args: {
  
  
  
    story: `
    // Your story content goes here. This is rendered as a child of the component
    `
  },
  parameters: {
// <!-- PARAMETERS --->
    docs: {
      // figure out what the hell this thing does
      description: {
        component: ``,
      },
      source: {
        // This code sample will be used for every example unless overridden.
        code: `
<test-component
// <!-- DOC ATTRIBUTES --->
>
// <!-- SLOT CONTENT --->
</test-component>
        `,
      },
    },
  },
};
